### ISSUE TITLE
fonts are missing from repo

### ISSUE THREAD

**Issue by iddq** [dinodork/zx-fonts#1]
fonts are missing from repo

**Comment by dinodork** [comment]
I'm sorry, I don't see what you mean?

**Comment by iddq** [comment]
I apologize, but based on the name, I thought there would be a lot of fonts in this repo, and since I didn’t notice those 3 pieces, I assumed the fonts disappeared :)

**Comment by dinodork** [comment]
Feel free to contribute fonts, though! This was just a trip down memory lane for me. Some of these fonts I created when I was ten and they have been salvaged from old tapes!
